
import Sidebar from '@/components/app-bar/Sidebar'
import MainFeed from '@/components/feed/MainFeed'
import Widgets from '@/components/widget/widgets'
import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex min-h-screen max-w-7xl mx-auto'>
        <Sidebar/>
        <MainFeed />
        <Widgets />
      </main>
    </>
  )
}
